### ISSUE TITLE
has no method 'devices'    at swig.renderFile.upnp (/usr/local/lib/node_modules/homestar/app/app.js:243:42)

### ISSUE THREAD

**Issue by neversay** [dpjanes/iotdb-homestar#1]
I hit upnp link in the page in my local machine, and got this error info:
TypeError: Object function () {
   if (!_upnp) {
       _upnp = require('iotdb-upnp');
   }

   return _upnp;
} has no method 'devices'
   at swig.renderFile.upnp (/usr/local/lib/node_modules/homestar/app/app.js:243:42)
   at eval (eval at <anonymous> (/usr/local/lib/node_modules/homestar/node_modules/swig/lib/swig.js:498:13), <anonymous>:23:108)
   at Object.eval [as tpl] (eval at <anonymous> (/usr/local/lib/node_modules/homestar/node_modules/swig/lib/swig.js:498:13), <anonymous>:48:3)
   at compiled (/usr/local/lib/node_modules/homestar/node_modules/swig/lib/swig.js:619:18)
   at Object.renderFile (/usr/local/lib/node_modules/homestar/node_modules/swig/lib/swig.js:570:38)
   at /usr/local/lib/node_modules/homestar/app/app.js:233:30
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homestar/node_modules/express/lib/router/layer.js:82:5)
   at next (/usr/local/lib/node_modules/homestar/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/usr/local/lib/node_modules/homestar/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homestar/node_modules/express/lib/router/layer.js:82:5)

Hope it helps.

**Comment by dpjanes** [comment]
Thanks! _Literally_ just finishing up a major overhaul, will make sure this works and will be back ASAP (i.e. probably tomorrow).

**Comment by neversay** [comment]
well take it easy, it is weekend :)

Just one note regarding to homestar intstall, when I tried to use homestar install to download cookbook file, it failed since npm cannot download single js file. maybe a guideline to download js file by wget and install it into the target folder by describing the file path?

**Comment by dpjanes** [comment]
I'm trying!

I've been changing _install_ so it actually installs npm packages, plus
keeps a registry of this. The idea is that instead of loading giant
packages with everything you need, you just pick and choose.

Have a look e.g. at this
https://github.com/dpjanes/homestar-wemo

What's documented as _install_ has become *add-recipe, *though I'm hoping
it'll be able to share recipes via npm also - basically, recipes as apps.

Please join up here if you have the chance
https://plus.google.com/communities/108112460238486371606

D.

**Comment by neversay** [comment]
yap, I am in the group :)

**Comment by dpjanes** [comment]
This should be fixed now. Make sure to get the latest homestar. Then do "homestar setup" and that will install iotdb in ./node_modules and everything should be up to date.

Note that the require('homestar') stuff for the cookbooks is going to become require('iotdb'). Working on this next.

**Comment by neversay** [comment]
still no luck. Here is the error stack:

TypeError: undefined is not a function
    at swig.renderFile.upnp (/usr/local/lib/node_modules/homestar/app/app.js:243:37)
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/homestar/node_modules/swig/lib/swig.js:498:13), <anonymous>:24:108)
    at Object.eval [as tpl] (eval at <anonymous> (/usr/local/lib/node_modules/homestar/node_modules/swig/lib/swig.js:498:13), <anonymous>:49:3)
    at compiled (/usr/local/lib/node_modules/homestar/node_modules/swig/lib/swig.js:619:18)
    at Object.renderFile (/usr/local/lib/node_modules/homestar/node_modules/swig/lib/swig.js:570:38)
    at /usr/local/lib/node_modules/homestar/app/app.js:233:30
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homestar/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/homestar/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/lib/node_modules/homestar/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/homestar/node_modules/express/lib/router/layer.js:82:5)

**Comment by neversay** [comment]
And when I try to run the script with new version, it crashed immediately:

things = iot.connect("WeMoSocket")
{"name":"iotdb","module":"things","hostname":"nailfamous-lm","pid":3457,"level":30,"method":"connect","modeld":"WeMoSocket","msg":"called","time":"2015-03-02T06:40:41.207Z","v":0}
{ array_id: '__thing_array_1',
  length: 0,
  transaction_depth: 0,
  _things: 
   { paramd: {},
     _thingd: {},
     _bridge_exemplars: [],
     domain: null,
     _events: { thing: [Object] },
     _maxListeners: 0 },
  _persistds: [],
  domain: null,
  _events: {},
  _maxListeners: 128 }

/Users/neversay/temp/node_modules/homestar-wemo/WeMoSocketBridge.js:67
    var cp = iotdb.module("iotdb-upnp").control_point();
                   ^
TypeError: Object #<Object> has no method 'module'
    at WeMoSocketBridge.discover (/Users/neversay/temp/node_modules/homestar-wemo/WeMoSocketBridge.js:67:20)
    at /Users/neversay/temp/node_modules/iotdb/things.js:186:25
    at process._tickCallback (node.js:415:13)

It happens on both my Mac and Raspberry PI.

**Comment by dpjanes** [comment]
Ough. The problem was dependence on an old version of IOTDB, plus it
doesn't force the installation of "iotdb-upnp".

This sort of setup should work now:

$ npm install -g homestar
$ homestar setup
$ homestar runner

I'm not sure if the Cookbook function is working yet, but Things and UPnP
should be now. You have to install the particular modules for things you
want to work with:

$ homestar install homestar-wemo
$ homestar install homestar-hue

D.

**Comment by neversay** [comment]
BTW, alway got error info during running homestar commands:
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

**Comment by dpjanes** [comment]
Thanks. I'm seeing that one too on my fresh builds, but it's not impacting
anything that I can see. I think it's something to do with bunyan. Ideally
I would remove all dependencies on a C compiler being around so it can go
onto Yuns, etc..

D

**Comment by neversay** [comment]
yap it works :)

**Comment by dpjanes** [comment]
Yayyyy!!!
